version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: hospital_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hospital_management}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_network
    restart: unless-stopped

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: hospital_backend
    command: gunicorn hospital_api.wsgi:application --bind 0.0.0.0:8000 --config gunicorn.conf.py
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secure_password}@db:5432/${POSTGRES_DB:-hospital_management}
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    depends_on:
      - db
    networks:
      - hospital_network
    restart: unless-stopped

  # React Frontend (built and served by nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: hospital_frontend
    volumes:
      - frontend_build:/app/dist
    networks:
      - hospital_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./deployment/nginx
      dockerfile: Dockerfile
    container_name: hospital_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - frontend_build:/var/www/html
      - ./deployment/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - hospital_network
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_build:

networks:
  hospital_network:
    driver: bridge
