# Generated by Django 4.2.7 on 2025-06-23 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receptionist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receptionist_id", models.CharField(max_length=20, unique=True)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=100)),
                (
                    "desk_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "shift_preference",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Shift (6AM-2PM)"),
                            ("afternoon", "Afternoon Shift (2PM-10PM)"),
                            ("evening", "Evening Shift (10PM-6AM)"),
                            ("rotating", "Rotating Shifts"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("languages_spoken", models.JSONField(blank=True, default=list)),
                ("computer_skills", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "system_access_level",
                    models.CharField(default="basic", max_length=50),
                ),
                ("can_schedule_appointments", models.BooleanField(default=True)),
                ("can_handle_billing", models.BooleanField(default=False)),
                ("can_access_medical_records", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "receptionist"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_receptionists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "receptionist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptionist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receptionist",
                "verbose_name_plural": "Receptionists",
            },
        ),
        migrations.CreateModel(
            name="Pharmacist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmacist_id", models.CharField(max_length=20, unique=True)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "pharmacist_level",
                    models.CharField(
                        choices=[
                            ("staff", "Staff Pharmacist"),
                            ("clinical", "Clinical Pharmacist"),
                            ("consultant", "Consultant Pharmacist"),
                            ("chief", "Chief Pharmacist"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "pharmacy_school",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                ("degree_type", models.CharField(blank=True, max_length=50, null=True)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("license_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("consultant", "Consultant"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("department", models.CharField(default="Pharmacy", max_length=100)),
                (
                    "pharmacy_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "can_dispense_controlled_substances",
                    models.BooleanField(default=True),
                ),
                (
                    "can_provide_clinical_consultations",
                    models.BooleanField(default=False),
                ),
                ("can_modify_prescriptions", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "pharmacist"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_pharmacists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "pharmacist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacist",
                "verbose_name_plural": "Pharmacists",
            },
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nurse_id", models.CharField(max_length=20, unique=True)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "nursing_level",
                    models.CharField(
                        choices=[
                            ("cna", "Certified Nursing Assistant"),
                            ("lpn", "Licensed Practical Nurse"),
                            ("rn", "Registered Nurse"),
                            ("bsn", "Bachelor of Science in Nursing"),
                            ("msn", "Master of Science in Nursing"),
                            ("np", "Nurse Practitioner"),
                        ],
                        default="rn",
                        max_length=10,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                ("specializations", models.JSONField(blank=True, default=list)),
                (
                    "nursing_school",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("license_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("per_diem", "Per Diem"),
                            ("travel", "Travel Nurse"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "shift_preference",
                    models.CharField(
                        choices=[
                            ("day", "Day Shift (7AM-7PM)"),
                            ("night", "Night Shift (7PM-7AM)"),
                            ("rotating", "Rotating Shifts"),
                            ("on_call", "On-Call"),
                        ],
                        default="day",
                        max_length=20,
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "nurse"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_nurses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "nurse"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nurse",
                "verbose_name_plural": "Nurses",
            },
        ),
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_id", models.CharField(max_length=20, unique=True)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("system_admin", "System Administrator"),
                            ("department_admin", "Department Administrator"),
                            ("data_admin", "Data Administrator"),
                        ],
                        default="system_admin",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "office_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "office_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("system_permissions", models.JSONField(blank=True, default=dict)),
                ("last_system_access", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
            },
        ),
    ]
