# Generated by Django 4.2.7 on 2025-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user with this email address already exists."
                },
                help_text="Required. Enter a valid email address.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
