# Generated by Django 4.2.7 on 2025-06-21 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head_of_department",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_headed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "doctors_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
                "db_table": "doctors_specialization",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.CharField(max_length=20, unique=True)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "medical_school",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                (
                    "residency_program",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fellowship_program",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("consultant", "Consultant"),
                            ("resident", "Resident"),
                            ("intern", "Intern"),
                            ("retired", "Retired"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard consultation fee",
                        max_digits=8,
                    ),
                ),
                (
                    "is_accepting_patients",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the doctor is currently accepting new patients",
                    ),
                ),
                (
                    "max_patients_per_day",
                    models.IntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Professional certifications and credentials",
                        null=True,
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(
                        blank=True, help_text="Areas of research interest", null=True
                    ),
                ),
                (
                    "publications",
                    models.TextField(
                        blank=True,
                        help_text="Notable publications and research papers",
                        null=True,
                    ),
                ),
                (
                    "awards",
                    models.TextField(
                        blank=True, help_text="Awards and recognitions", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="doctors.department",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True, related_name="doctors", to="doctors.specialization"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctors_doctor",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor_id"], name="doctors_doc_doctor__db23fb_idx"
                    ),
                    models.Index(
                        fields=["license_number"], name="doctors_doc_license_3eaac3_idx"
                    ),
                    models.Index(
                        fields=["department"], name="doctors_doc_departm_6f8e45_idx"
                    ),
                    models.Index(
                        fields=["employment_status"],
                        name="doctors_doc_employm_7a05be_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="doctors_doc_is_acti_3a5153_idx"
                    ),
                    models.Index(
                        fields=["is_accepting_patients"],
                        name="doctors_doc_is_acce_b4ef5b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="doctors_dep_name_b00d66_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="doctors_dep_is_acti_db7244_idx"
            ),
        ),
    ]
