# Generated by Django 4.2.7 on 2025-06-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_fix_department_unique_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="department",
            name="unique_active_department_name",
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
